added a feature where, if deluge gets focus with a new torrent url on the clipboard, the add torrent from url dialog will pop up
deluge-torrent/deluge pull request #306
Opened 2021-02-15 19:23 UTC by matiasw

There is a feature in Transmission Remote GUI that pops up the "Add torrent" dialog automatically if it detects that there is a torrent URL on the clipboard when the program gets focus. This is a preliminary implementation of that feature in Deluge.

At the moment, it works, but it does not have the intelligence to check if the torrent on the clipboard is already being downloaded. On IRC, I was adviced to "grab the .torrent and check to see if the hash already exists", but this seems like a rather heavy operation to perform each time the program gets focus with a torrent URL on the clipboard.

2021-02-20 22:10 UTC, DjLegolas requested changes
Please fix the code formatting errors (from `lint`):
1. fix `import`s order
2. use only single-quote

Best way is to run the `tox` tests yourself.

In addition, please change the commit message as it is too long for one line.
Something like:
```
[GTKUI] Added detection of torrent URL on GTK UI focus

In case deluge GTK gets focus with a new torrent URL on the clipboard, the "Add Torrent from URL" dialog will pop up automatically
```

2021-02-21 05:14 UTC, matiasw commented
@DjLegolas Thanks for the feedback. I changed quotes into single quotes and changed the import order; not sure if it's still the way you'd like?

2021-02-21 10:23 UTC, DjLegolas requested changes

2021-02-21 10:23 UTC, DjLegolas commented on deluge/ui/gtk3/mainwindow.py
> +from gi.repository import Gtk, Gdk
Just switch the order like this:
```python
from gi.repository import Gdk, Gtk
```

2021-02-21 10:49 UTC, matiasw commented on deluge/ui/gtk3/mainwindow.py
> +from gi.repository import Gtk, Gdk
Ok, done.

2021-08-19 12:29 UTC, Erarshad commented
https://github.com/CCExtractor/Deluge-mobile-remote-client
now deluge mobile client is also available for android and ios. it is open source fork repository give star and feel free to send PR

2021-09-25 07:07 UTC, cas-- requested changes

2021-09-25 13:29 UTC, matiasw commented
Ok, so I changed the code to use these premade functions. It is a bit neater, now.

2021-09-25 16:35 UTC, cas-- requested changes
Looking much better, can we do some final linting cleanup. Use `isort` to auto-fix the linting issues. 

I was just testing it out and wonder if this should be a user preference since without any way for the user to disable it might be annoying. 

You can search for the `gtkui_config['show_piecesbar']` preference to use as a guide to implementing it.

![image](https://user-images.githubusercontent.com/606038/134777752-15000708-117a-4827-8606-241ed834c900.png)

2021-09-26 15:32 UTC, matiasw commented
I have made the requested modifications and added the Preferences setting for this feature.

2021-09-26 16:36 UTC, cas-- commented
Excellent, thanks! Just need to fix the failing linting issues

![image](https://user-images.githubusercontent.com/606038/134816146-779a9b67-c27f-4e79-affc-2d96f0c4295e.png)

If you install [pre-commit](pre-commit.com) then your commits are linted automatically

2021-09-26 18:01 UTC, matiasw commented
Uh, so, I did install pre-commit, and on my machine, with `pre-commit run --all-files`, I get all PASSED, but the CI test on Github still fails. If I knew why, I could fix it?

2021-09-26 18:23 UTC, cas-- commented
That is strange, I see this: 

![image](https://user-images.githubusercontent.com/606038/134819581-c601db75-734b-4839-8322-d53e989e3503.png)

Don't worry I'll can resolve it when merging it :+1:

2021-10-03 18:49 UTC, closed without merging

2021-10-03 18:53 UTC, cas-- commented
Thanks @matiasw for this useful feature!