Add the torrent label to the console info command
deluge-torrent/deluge pull request #356
Opened 2022-02-02 08:22 UTC by kingamajick

Outputs the torrent's label when the detailed (or verbose) info is requested from deluge-console. This makes is easily accessible in scripts (such as those used by the execute plugin)

Closes: https://dev.deluge-torrent.org/ticket/1556

2022-02-02 14:19 UTC, gazpachoking commented
Hmm. The labels come from a plugin, it feels weird to reference them directly in the core of the client. OTOH, I don't think we have any plugin support for console client... I think if it's even to be considered this has to not fail when the label plugin is not enabled. Also, it looks like the download folder output is overwritten by the label in this current incarnation.

2022-02-02 15:48 UTC, cas-- requested changes
Needs work as @gazpachoking said

2022-02-02 16:21 UTC, kingamajick commented
Thanks for the feedback, i've updated it such that it will work both in the case that the label plugin is either enabled or disabled. I've also corrected the mistake where it would overwrite the download folder :)

2022-02-05 20:01 UTC, cas-- approved these changes

2022-02-06 16:25 UTC, closed without merging