Add a systemd user service
deluge-torrent/deluge pull request #380
Opened 2022-02-22 23:20 UTC by WhyNotHugo

This file should be installed into /usr/lib/systemd/user/deluged.service

Unlike the existing service file, this one configures deluge to run as a desktop session user. It does not require root privileges to be controlled either.

2022-02-23 17:24 UTC, cas-- commented
When adding the service file to the code I discussed that there was no need for a separate user service file since they are identical service files: https://dev.deluge-torrent.org/ticket/2034#comment:13

I'm not seeing anything here that would change that? Maybe what is missing is additional documentation for installing a user service file?

2022-02-23 18:51 UTC, WhyNotHugo commented
They have some differences identical: the user service includes a `Slice` and depends on a different target (the user service manager and system service manager have different targets). Copying one into the others location won't work.

2022-02-23 20:03 UTC, cas-- commented
Ah I was unaware that user service doesn't include `multi-user.target`. Would setting the service to use `default.target` be a solution as I see it is usually symlinked to multi-user anyway? I know that the `wantedby` can be overridden but could that be more complicated that a separate service file :thinking: 

Why include `Slice`, I not sure I see the benefit here for the single deluged service? And why only for the user service?

2022-02-23 20:18 UTC, WhyNotHugo commented
Including the Slice indicates to the service manager that this is a background service. This can be used to handle OOM situations, or prioritising foreground processes. There's no equivalent for system services.

I'm not sure about pulling the system service for `default.target`; I don't know how that interoperates when booting into rescue mode or other special modes. It might be fine, but I can't guarantee it.

Ultimately though, shipping the two distinct files makes life easier for packagers of systemd-based distros since it signals that they can just copy both of them to their respective locations. I would also like to include a `sysusers` file for the system service to automatically handle that user (mostly to de-duplicate work that being repeated downstream). I'd rather tackle that last item separately though to scope the PRa better.

2022-02-23 20:55 UTC, cas-- commented
Okay this change makes sense, thanks for details.

We would need the same for web service though

2022-02-24 11:14 UTC, cas-- requested changes
If we are adding a deluged user service then we should also add a deluge-web user service

2022-02-24 11:14 UTC, cas-- commented on packaging/systemd/deluged.service
> +Documentation=man:deluged(1)
We don't need the section number, it's optional and would open at 1 anyway

2022-03-02 11:41 UTC, closed without merging

2022-03-02 15:57 UTC, WhyNotHugo commented
Thanks for wrapping this one up. :+1: