[Web] Accept charset in content-type for json messages
deluge-torrent/deluge pull request #385
Opened 2022-05-28 07:32 UTC by ibizaman

Trac: https://dev.deluge-torrent.org/ticket/3521

2022-05-28 12:00 UTC, cas-- requested changes
Thanks for reporting and suggesting a fix, I have provided some feedback to improve it

2022-05-28 18:45 UTC, ibizaman commented on deluge/ui/web/json_api.py
> +        content_type, charset = self._parse_content_type(request.getHeader(b'content-type').decode())
Good call. I agree with your proposal although TBH I don’t know which one to choose.

Being more strict and asserting the charset to be utf-8 would probably avoid some headaches down the line by failing early.

But on the other side being more lenient can avoid badly configured clients to be blocked.

My gut tells me being stricter is better but what do you think? Are there some similar choices that had been made on the past?

2022-05-28 18:53 UTC, ibizaman commented on deluge/tests/test_webserver.py
> +    def _test_get_torrent_info(self, content_type):
Ah I totally missed that. I’ll change it.

2022-05-28 19:33 UTC, cas-- commented on deluge/ui/web/json_api.py
> +        content_type, charset = self._parse_content_type(request.getHeader(b'content-type').decode())
It's safe to assume that all `application/json` content type will be `utf-8`, in fact the charset parameter is not part of the standard: https://github.com/request/request/issues/383#issuecomment-18455635

So let's keep it simple, you could still use `cgi.parse_header` and ignore the second tuple value using the `_`:

```
content_type, _ = cgi.parse_header(header-content-type)
```

2022-05-28 23:23 UTC, ibizaman commented on deluge/ui/web/json_api.py
> +        content_type, charset = self._parse_content_type(request.getHeader(b'content-type').decode())
Oh I had no idea about that. Cool let’s keep it simple. I’ll definitely add a comment about it.

2022-05-29 06:05 UTC, ibizaman commented on deluge/tests/test_webserver.py
> +    def _test_get_torrent_info(self, content_type):
So instead, I wanted to check that the content-type was valid for `application/json` and `application/json;charset=utf-8` so I created a new test function for it. I'm happy to change that in any way, just tell me.

2022-05-29 12:24 UTC, cas-- commented on deluge/ui/web/json_api.py
> +        # the `utf-8` charset.
I appreciate the addition of a comment but without any context about charset it is not worth mentioning here as comment. We should always err towards less comments unless the code we write is unclear but even then refactoring the code might help. 

The actual reasoning for making this change should be stored in the git commit message so we then use git blame in future if we are uncertain about this line of code. We also have the tests that could improved with a docstring to quickly outline reasoning.



I prefer that the test docstring mentions this and in the commit message provides more details about reasoning.

2022-05-29 12:28 UTC, cas-- commented on deluge/tests/test_json_api.py
> +    def test_on_json_request_valid_content_type(self):
I would split this into two tests, helps with understanding should a test fail
```
test_on_json_request_content_type
"""Ensure content-type application/json is accepted"""

test_on_json_request_content_type_charset
"""Ensure content-type parameters such as charset are ignored"""
```

2022-05-30 09:06 UTC, cas-- approved these changes
Thanks for patience with this, looks excellent :+1:

2022-05-30 14:58 UTC, ibizaman commented
@cas--  With pleasure!

2022-06-12 15:09 UTC, closed without merging

2022-06-12 16:36 UTC, ibizaman commented
Thanks @cas--