[Console] Fix saving preferences
deluge-torrent/deluge pull request #445
Opened 2024-03-19 12:58 UTC by mhertz

2024-08-24 16:28 UTC, cas-- commented
It is good to explain the problem that is being solved in the commit message because it is not always self-evident and it took a while for me to understand this issue.

I can see now that the preferences close dialog actions by default requires a two-step action, first select one-of `Cancel`, `Apply`, `Ok` with space then hit enter. This is probably counter-intuitive to what the user expects and since the default action is cancel their changes to preferences are lost. I can see that your fix would work but I feel the correct fix here is to set the `SelectInput` arg `require_select_action` to `False` thus explicitly denoting the type of action we require. 

There is a second more subtle issue where if the user hits cancel in preferences then the changes made are not discarded so the user might still think those preferences have been saved. Something a bit hacky like this should solve it: 

```diff
-    def _update_preferences(self, core_config):
+    def _update_preferences(self, core_config, console_config=None):
         self.core_config = core_config
         for pane in self.panes:
-            pane.update_values(core_config)
+            if isinstance(pane, InterfacePane) and console_config:
+                pane.update_values(console_config)
+            else:
+                pane.update_values(core_config)
 
     def _actions_read(self, c):
         self.action_input.handle_read(c)
         if c in [curses.KEY_ENTER, util.KEY_ENTER2]:
             # take action
             if self.action_input.selected_index == 0:  # Cancel
+                # Reload stored config for panes
+                self._update_preferences(self.core_config, self.console_config)
                 self.back_to_parent()
             elif self.action_input.selected_index == 1:  # Apply
                 self._apply_prefs()
```



This also raises the question about how the preference panes are refreshed when other interfaces update the core config since it appears core config is only loaded once per session (unless Apply selected).

2024-08-24 16:34 UTC, cas-- requested changes
See above comment

2024-08-25 18:53 UTC, mhertz commented
I'm sorry Cas, I didn't actually understood those where checkboxes and thought regular buttons(so return/enter only), so thought actual bug and not just usability issue, thanks for explaining, appreciated and i'll try be better with verbosity, which agreed particularly bad here, despite my confusion.

As said before, if feel faster for you to just make yourself (here/elsewhere) then please just close and don't need explain, little anxious about being a nuisance honestly :) You understand hopefully. Thanks!

2024-08-26 18:43 UTC, closed without merging

2024-08-26 18:45 UTC, cas-- commented
Thanks for understanding, these are helpful commits and I am happy to have the discussion to ensure the changes are what we expect them to be :)