[WebUI]Fix Connection Manager stop daemon, return 5 elem from get_host_info()
deluge-torrent/deluge pull request #452
Opened 2024-05-13 04:49 UTC by ppayne

Attempting to stop the daemon from Connection Manager in the WebUI would throw an error "An error occurred". On deeper inspection this was because this line threw a ValueError expecting 4 items but only getting 3:

```python
host, port, user, password = host[1:5]
```

This fix updates the `get_host_info()` function to also return password.

2024-05-13 04:49 UTC, ppayne commented
Tested locally, now successfully stops and starts the daemon from Connection Manager.

2024-07-20 15:09 UTC, cas-- requested changes

2024-07-20 15:09 UTC, cas-- commented on deluge/ui/hostlist.py
> +            list: A list of (host_id, hostname, port, username, password).
It's a bit of a red flag to return a cleartext password to solve this issue. I think the correct solution is to use `hostlist.connect_host` in `json_api.stop_daemon`

2024-08-24 10:21 UTC, cas-- commented
Fixed via 1e5f248fb88804030df70cc511094888de4bd77f

2024-08-24 10:21 UTC, closed without merging