Fix name of Ubuntu prerequisite
deluge-torrent/deluge pull request #459
Opened 2024-08-24 18:32 UTC by kenstir

Change name to gir1.2-appindicator3-0.1.  Tested on Ubuntu 22.04.4 LTS and Ubuntu 20.04.6 LTS.

2024-08-24 18:54 UTC, cas-- requested changes
We actually support the newer `AyatanaAppIndicator3` so would be better to update to [gir1.2-ayatanaappindicator3-0.1](https://packages.ubuntu.com/focal/gir1.2-ayatanaappindicator3-0.1). Also if you do a quick search I think there is another reference in the docs that could be updated

2024-08-24 19:29 UTC, kenstir reviewed
self check: pass

2024-08-26 14:31 UTC, cas-- commented on DEPENDS.md
> +[ayatanaappindicator3]: https://packages.ubuntu.com/jammy/gir1.2-ayatanaappindicator3-0.1
Actually I think this page would be better: https://lazka.github.io/pgi-docs/AyatanaAppIndicator3-0.1/index.html

2024-08-26 15:11 UTC, kenstir commented on DEPENDS.md
> +[ayatanaappindicator3]: https://packages.ubuntu.com/jammy/gir1.2-ayatanaappindicator3-0.1
That makes sense.  Done.

2024-08-26 18:40 UTC, closed without merging

2024-08-26 19:45 UTC, cas-- commented
Thanks for the PR :+1: