Fix bug in AuthenticationDialog
deluge-torrent/deluge pull request #463
Opened 2024-08-30 23:15 UTC by Jaywalker

Specific bug is described here: https://dev.deluge-torrent.org/ticket/3643#ticket

The issue occured because the `AuthenticationDialog` was `destroy()`'d before the calls were made to get the text from their `GTK.Entry()`'s. It has been fixed by using the same method as `AccountDialog` and storing the information in an `Account` object prior to the `destroy()` call.

It may be worth considering giving the user an option to save/update the `hostlist.conf`  file with the working credentials as well, but that would merit discussion and a separate PR. This PR simply fixes the problem and leaves existing logic flow in place.

2024-09-03 19:24 UTC, cas-- requested changes
Thanks for this, I imagine this will also affect PasswordDialog so would be useful to fix there too

2024-09-03 19:27 UTC, cas-- commented on AUTHORS
> +    * Justin Williams ('Jaywalker')
This list is really for authors of significant contributions to Deluge

2024-09-06 05:54 UTC, zakkarry requested changes
Two linting issues by the way, figured I'd point them out.

2024-09-06 05:54 UTC, zakkarry commented on deluge/ui/gtk3/connectionmanager.py
> +                    self._connect(host_id, dialog.account.username, dialog.account.password)
```suggestion
                    self._connect(
                        host_id, dialog.account.username, dialog.account.password
                    )
```

2024-09-06 05:54 UTC, zakkarry commented on deluge/ui/gtk3/dialogs.py
> +                "",
```suggestion
                '',
```

2025-08-21 21:26 UTC, cas-- commented
Forgot about this PR and actually fixed it separately while resolving same issue with tray password: https://github.com/deluge-torrent/deluge/commit/88e6bbc1335c8d4c8ac2ee2152f3d23e931034f1

2025-08-21 21:26 UTC, closed without merging